name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  create:
    tags: [v*]

permissions:
  contents: read

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Pull all history with tags for correct versionning
      run: git fetch --prune --unshallow
    - name: Format check
      run: ./scala fmt --check .
    - name: Tests
      run: ./scala test .
    - name: Publish
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v') || github.event_name == 'release'
      run: |
        ./scala --power publish --organization=com.goyeau \
                                --name=moulin \
                                --description="Build multi-projects with Scala CLI" \
                                --developer="joan38|Joan Goyeau|https://github.com/joan38" \
                                --license=Apache-2.0:https://spdx.org/licenses/Apache-2.0.html \
                                --url=https://github.com/joan38/moulin \
                                --vcs="https://github.com/joan38/moulin|scm:git:https://github.com/joan38/moulin.git|scm:git:https://github.com/joan38/moulin.git" \
                                --compute-version=git:dynver \
                                --publish-repository=sonatype \
                                --user=value:V3Bd3uEm \
                                --password=value:${{secrets.sonatype_password}} \
                                --secret-key="value:${{secrets.pgp_secret_key}}" \
                                .
